config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: 'home#index'

  resources :videos, only: %i[show]

  get 'login', to: 'sessions#index'
  post 'login', to: 'sessions#authenticate'
  delete 'login', to: 'sessions#destroy'
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  include ApplicationHelper

  private

  def zype_api
    Api::ZypeService.new(current_user_token)
  end
end

app/controllers/concerns/recursive_open_struct.rb
# frozen_string_literal: true

require 'ostruct'

module RecursiveOpenStruct
  def to_recursive_ostruct(hash)
    OpenStruct.new(hash.transform_values do |val|
      val.is_a?(Hash) ? to_recursive_ostruct(val) : val
    end)
  end
end

app/controllers/home_controller.rb
# frozen_string_literal: true

class HomeController < ApplicationController
  def index
    response = zype_api.videos(page: current_page)

    @pagination = response['pagination']
    @videos     = response['response']
    @presenters = @videos.map { |video| VideoPresenter.new(video) }
  end

  private

  def current_page
    params[:page] || 1
  end
end

app/controllers/sessions_controller.rb
# frozen_string_literal: true

class SessionsController < ApplicationController
  def index
    redirect_to :root if authenticated?
  end

  def authenticate
    response = zype_api.authenticate!(permitted_params[:username], permitted_params[:password])

    if response.success
      session[:user_token] = response.access_token
      session[:expires_at] = response.expires_in

      redirect_to :root
    else
      @authentication_error = response.message

      render :index
    end
  end

  def destroy
    session.clear

    redirect_to :root
  end

  private

  def permitted_params
    params.permit(:username, :password)
  end
end

app/controllers/videos_controller.rb
# frozen_string_literal: true

class VideosController < ApplicationController
  def show
    response = zype_api.videos(id: permitted_params[:id])

    @video = response['response'].first
    @presenter = VideoPresenter.new(@video)
  end

  private

  def permitted_params
    params.permit(:id)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
  def current_user_token
    session[:user_token]
  end

  def authenticated?
    current_user_token.present?
  end
end

app/helpers/pagination_helper.rb
# frozen_string_literal: true

module PaginationHelper
  def previous_page?
    @pagination.dig('previous').present?
  end

  def next_page?
    @pagination.dig('current') < @pagination.dig('pages')
  end
end

app/helpers/player_helper.rb
# frozen_string_literal: true

module PlayerHelper
  def zype_embed_player(video_id)
    embed_url = Api::ZypeService.new(current_user_token).embed_player_url(video_id)

    "<iframe src='#{embed_url}' width='500px' height='280px'>".html_safe
  end
end

app/views/home/_pagination_navbar.html.erb
<p>Current Page: <%= @pagination.dig('current') %> </p>

<p>
  <% if previous_page? %>
    <%= link_to "[Previous Page]", "?page=#{@pagination.dig('previous')}" %>
  <% end %>

  <% if next_page? %>
    <%= link_to "[Next Page]", "?page=#{@pagination.dig('next')}" %>
  <% end %>
</p>

app/views/home/index.html.erb
<%= render partial: 'pagination_navbar' if @pagination %>

<ul>
  <% @presenters.each do |video| %>
    <li>
      <p><a href="<%= video_path(video.id) %>"><%= video.title %></a></p>
      <p><small><%= Time.parse(video.created_at) %></small> <% if video.subscription_required %> <b>[SUBSCRIPTION REQUIRED]</b> <% end %></p>
      <p><a href="<%= video_path(video.id) %>"><img src="<%= video.thumbnails.first['url'] %>" alt="Minha Figura"></a></p>
    </li>
  <% end %>
</ul>

<hr>

<%= render partial: 'pagination_navbar' if @pagination %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ZypeTest</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% unless authenticated? %>
      <%= button_to "Login", login_path, method: :get %>
    <% else %>
      <p>You're authenticated</p>

      <%= button_to "Logout", login_path, method: :delete %>
    <% end %>

    <hr>

    <%= yield %>
  </body>
</html>

app/views/videos/show.html.erb
<p><a href="<%= root_path %>"><< Back</a></p>

<h1><%= @presenter.title %></h1>

<% if @presenter.subscription_required %>
  <p><b>[SUBSCRIPTION REQUIRED]</b></p>
<% end %>

<% unless @presenter.subscription_required && !authenticated? %>
  <%= zype_embed_player(@presenter.id) %>
<% else %>
  <p><a href="<%= login_path %>">Authenticate Here</a></p>
<% end %>